volumes:
  school_diary_local_postgres_data: {}
  school_diary_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: school_diary_local_django
    container_name: school_diary_local_django
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '${DJANGO_PORT:-8000}:8000'
        #command: /start
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: school_diary_production_postgres
    container_name: school_diary_local_postgres
    volumes:
      - school_diary_local_postgres_data:/var/lib/postgresql/data
      - school_diary_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: school_diary_local_mailpit
    ports:
      - "${MAILPIT_PORT:-8025}:8025"
