# Generated by Django 5.1.12 on 2025-10-05 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('submit', 'Submitted'), ('cancel', 'Cancelled'), ('custom', 'Custom')], max_length=20, verbose_name='Event Type')),
                ('event_name', models.CharField(help_text='Human-readable event name', max_length=200, verbose_name='Event Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event', verbose_name='Description')),
                ('model_name', models.CharField(help_text='Name of the model that was changed', max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(help_text='ID of the object that was changed', max_length=100, verbose_name='Object ID')),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=200, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionary of field changes', verbose_name='Changes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'), models.Index(fields=['event_type'], name='audit_audit_event_t_4496ba_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx')],
            },
        ),
    ]
