# Generated by Django 5.1.12 on 2025-10-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': '監査ログ', 'verbose_name_plural': '監査ログ'},
        ),
    ]
