# Generated by Django 5.1.12 on 2025-10-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
