# Generated by Django 5.1.12 on 2025-09-25 12:18

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_demos', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_demos', to=settings.AUTH_USER_MODEL, verbose_name='申請者'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='status',
            field=django_fsm.FSMField(default='draft', max_length=50, verbose_name='ステータス'),
        ),
    ]
