# Generated by Django 5.1.12 on 2025-10-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_historicaldemorequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demorequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'サンプル申請', 'verbose_name_plural': 'サンプル申請'},
        ),
        migrations.AlterModelOptions(
            name='historicaldemorequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical サンプル申請', 'verbose_name_plural': 'historical サンプル申請'},
        ),
    ]
