# Generated by Django 5.1.12 on 2025-10-04 11:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='システム内で使用する一意の識別子(例: approval_request)', max_length=100, unique=True, verbose_name='テンプレートコード')),
                ('name', models.CharField(max_length=200, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('subject_template', models.CharField(help_text='Django Template構文が使えます: {{ user.name }}様', max_length=255, verbose_name='件名テンプレート')),
                ('body_template', models.TextField(help_text='プレーンテキストまたはMarkdown形式', verbose_name='本文テンプレート')),
                ('html_template', models.TextField(blank=True, help_text='HTMLメール用(オプショナル)', verbose_name='HTMLテンプレート')),
                ('notification_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'メール'), ('in_app', 'アプリ内通知'), ('push', 'プッシュ通知'), ('sms', 'SMS')], max_length=20), default=list, help_text='このテンプレートが対応する通知タイプ', size=None, verbose_name='通知タイプ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '通知テンプレート',
                'verbose_name_plural': '通知テンプレート',
                'db_table': 'kits_notification_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, help_text='Userモデルのemailと異なる場合に使用', max_length=254, verbose_name='受信者メールアドレス')),
                ('notification_type', models.CharField(choices=[('email', 'メール'), ('in_app', 'アプリ内通知'), ('push', 'プッシュ通知'), ('sms', 'SMS')], default='email', max_length=20, verbose_name='通知タイプ')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '通常'), ('high', '高'), ('urgent', '緊急')], default='normal', max_length=20, verbose_name='優先度')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('body', models.TextField(verbose_name='本文')),
                ('html_body', models.TextField(blank=True, verbose_name='HTML本文')),
                ('context_data', models.JSONField(default=dict, help_text='テンプレートに渡されたデータ', verbose_name='コンテキストデータ')),
                ('status', models.CharField(choices=[('pending', '送信待ち'), ('sending', '送信中'), ('sent', '送信完了'), ('failed', '送信失敗'), ('read', '既読')], default='pending', max_length=20, verbose_name='ステータス')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='指定した場合、この日時に送信されます', null=True, verbose_name='送信予定日時')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='リトライ回数')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name='関連オブジェクトタイプ')),
                ('related_object_id', models.CharField(blank=True, max_length=100, verbose_name='関連オブジェクトID')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='受信者')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'kits_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='kits_notifi_recipie_1972a5_idx'), models.Index(fields=['status', 'scheduled_at'], name='kits_notifi_status_8ebd7d_idx'), models.Index(fields=['created_at'], name='kits_notifi_created_faf018_idx')],
            },
        ),
    ]
