# Generated by Django 5.1.12 on 2025-10-08 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='前登校日の日付', verbose_name='記載日')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提出日時')),
                ('health_condition', models.IntegerField(choices=[(1, 'とても悪い'), (2, '悪い'), (3, '普通'), (4, '良い'), (5, 'とても良い')], default=3, verbose_name='体調')),
                ('mental_condition', models.IntegerField(choices=[(1, 'とても落ち込んでいる'), (2, '落ち込んでいる'), (3, '普通'), (4, '元気'), (5, 'とても元気')], default=3, verbose_name='メンタル')),
                ('reflection', models.TextField(help_text='今日あったこと、学んだこと、感じたことなど', verbose_name='今日の振り返り')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='既読者（担任）')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
            ],
            options={
                'verbose_name': '連絡帳エントリー',
                'verbose_name_plural': '連絡帳エントリー',
                'ordering': ['-entry_date', 'student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='家庭環境、健康情報、配慮事項など（長期的な観察記録）', verbose_name='メモ内容')),
                ('is_shared', models.BooleanField(default=False, help_text='学年の担任全員が閲覧できます', verbose_name='学年会議で共有')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes_about_me', to=settings.AUTH_USER_MODEL, verbose_name='対象生徒')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teacher_notes', to=settings.AUTH_USER_MODEL, verbose_name='担任')),
            ],
            options={
                'verbose_name': '担任メモ',
                'verbose_name_plural': '担任メモ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年')], verbose_name='学年')),
                ('class_name', models.CharField(choices=[('A', 'A組'), ('B', 'B組'), ('C', 'C組')], max_length=10, verbose_name='クラス名')),
                ('academic_year', models.IntegerField(default=2025, verbose_name='年度')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL, verbose_name='担任')),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
            ],
            options={
                'verbose_name': 'クラス',
                'verbose_name_plural': 'クラス',
                'ordering': ['academic_year', 'grade', 'class_name'],
                'unique_together': {('grade', 'class_name', 'academic_year')},
            },
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['entry_date'], name='diary_diary_entry_d_b5a90b_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['is_read'], name='diary_diary_is_read_b14fa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diaryentry',
            unique_together={('student', 'entry_date')},
        ),
    ]
