# Generated by Django 5.1.12 on 2025-10-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diaryentry_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='teacher_reaction',
            field=models.CharField(blank=True, choices=[('encourage', '👍 励まし'), ('commented', '💬 コメント済み'), ('needs_follow_up', '⚠️ 要フォロー'), ('confirmed', '✅ 確認済み'), ('parent_contacted', '📞 保護者連絡済み')], help_text='既読時に選択した対応アクション', max_length=20, null=True, verbose_name='担任の対応'),
        ),
    ]
