# Generated by Django 5.1.12 on 2025-10-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diaryentry_teacher_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='internal_action',
            field=models.CharField(blank=True, choices=[('needs_follow_up', '⚠️ 要フォロー'), ('urgent', '🔴 緊急対応必要'), ('parent_contacted', '📞 保護者連絡済み'), ('individual_talk', '🗣️ 個別面談実施'), ('shared_meeting', '👥 学年会議で共有'), ('monitoring', '📝 継続観察中'), ('resolved', '✅ 対応完了')], help_text='先生のみが見る対応状況（生徒には非表示）', max_length=20, null=True, verbose_name='対応記録'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='public_reaction',
            field=models.CharField(blank=True, choices=[('thumbs_up', '👍 いいね'), ('well_done', '💯 よくできました'), ('good_effort', '💪 がんばったね'), ('excellent', '🌟 素晴らしい'), ('support', '❤️ 応援してるよ'), ('checked', '📖 読んだよ')], help_text='生徒に表示されるポジティブな反応', max_length=20, null=True, verbose_name='生徒への反応'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='teacher_reaction',
            field=models.CharField(blank=True, choices=[('encourage', '👍 励まし'), ('commented', '💬 コメント済み'), ('needs_follow_up', '⚠️ 要フォロー'), ('confirmed', '✅ 確認済み'), ('parent_contacted', '📞 保護者連絡済み')], help_text='非推奨: public_reaction と internal_action を使用', max_length=20, null=True, verbose_name='担任の対応（非推奨）'),
        ),
    ]
