# Generated by Django 5.1.12 on 2025-10-11 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diaryentry_internal_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='action_completed_at',
            field=models.DateTimeField(blank=True, help_text='対応完了にした日時', null=True, verbose_name='対応完了日時'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='action_completed_by',
            field=models.ForeignKey(blank=True, help_text='対応完了にした担任', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_diary_actions', to=settings.AUTH_USER_MODEL, verbose_name='対応者'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='action_status',
            field=models.CharField(choices=[('pending', '未対応'), ('in_progress', '対応中'), ('completed', '対応済み'), ('not_required', '対応不要')], default='pending', help_text='internal_actionの対応状況を管理', max_length=20, verbose_name='対応状況'),
        ),
    ]
