# Generated by Django 5.1.12 on 2025-10-12 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diaryentry_action_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='action_note',
            field=models.CharField(blank=True, help_text='どのように対応したかを簡潔に記録（引継ぎ・保護者面談で活用）', max_length=200, null=True, verbose_name='対応内容メモ'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='internal_action',
            field=models.CharField(blank=True, choices=[('needs_follow_up', '⚠️ 要フォロー'), ('urgent', '🔴 緊急対応必要'), ('parent_contacted', '📞 保護者連絡'), ('individual_talk', '🗣️ 個別面談'), ('shared_meeting', '👥 学年共有'), ('monitoring', '📝 継続観察')], help_text='先生のみが見る対応状況（生徒には非表示）', max_length=20, null=True, verbose_name='対応記録'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['action_status'], name='diary_diary_action__897a34_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['internal_action'], name='diary_diary_interna_d3e31f_idx'),
        ),
    ]
