# Generated by Django 5.1.12 on 2025-10-12 00:06

from django.db import migrations


def cleanup_resolved_data(apps, schema_editor):
    """
    既存のinternal_action='resolved'データをクリーンアップ
    - internal_actionをNoneに変更
    - action_statusは既にcompletedになっているはず
    """
    DiaryEntry = apps.get_model('diary', 'DiaryEntry')
    DiaryEntry.objects.filter(internal_action='resolved').update(
        internal_action=None,
    )


def reverse_cleanup(apps, schema_editor):
    """ロールバック時の処理（何もしない）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diaryentry_action_note_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_resolved_data, reverse_cleanup),
    ]
