# Generated by Django 5.1.12 on 2025-10-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_cleanup_resolved_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='記載時の所属クラス（年度・学年・組）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diary_entries', to='diary.classroom', verbose_name='所属クラス'),
        ),
    ]
