# Generated by Django 5.1.12 on 2025-10-13 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_diaryentry_classroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '生徒'), ('teacher', '担任'), ('grade_leader', '学年主任'), ('school_leader', '教頭/校長')], default='student', help_text='ユーザーの役割（アクセス権限を自動的に設定）', max_length=20, verbose_name='役割')),
                ('managed_grade', models.IntegerField(blank=True, help_text='学年主任の場合、管理する学年（1, 2, 3）', null=True, verbose_name='管理学年')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
    ]
