# Generated by Django 5.1.12 on 2025-10-13 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='managed_grade',
            field=models.IntegerField(blank=True, help_text='学年主任の場合、管理する学年（1, 2, 3）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='管理学年'),
        ),
    ]
