# Generated by Django 5.1.12 on 2025-10-13 06:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_userprofile_managed_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDiaryEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='前登校日の日付', verbose_name='記載日')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提出日時')),
                ('health_condition', models.IntegerField(choices=[(1, 'とても悪い'), (2, '悪い'), (3, '普通'), (4, '良い'), (5, 'とても良い')], default=3, verbose_name='体調')),
                ('mental_condition', models.IntegerField(choices=[(1, 'とても落ち込んでいる'), (2, '落ち込んでいる'), (3, '普通'), (4, '元気'), (5, 'とても元気')], default=3, verbose_name='メンタル')),
                ('reflection', models.TextField(help_text='今日あったこと、学んだこと、感じたことなど', verbose_name='今日の振り返り')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('teacher_reaction', models.CharField(blank=True, choices=[('encourage', '👍 励まし'), ('commented', '💬 コメント済み'), ('needs_follow_up', '⚠️ 要フォロー'), ('confirmed', '✅ 確認済み'), ('parent_contacted', '📞 保護者連絡済み')], help_text='非推奨: public_reaction と internal_action を使用', max_length=20, null=True, verbose_name='担任の対応（非推奨）')),
                ('public_reaction', models.CharField(blank=True, choices=[('thumbs_up', '👍 いいね'), ('well_done', '💯 よくできました'), ('good_effort', '💪 がんばったね'), ('excellent', '🌟 素晴らしい'), ('support', '❤️ 応援してるよ'), ('checked', '📖 読んだよ')], help_text='生徒に表示されるポジティブな反応', max_length=20, null=True, verbose_name='生徒への反応')),
                ('internal_action', models.CharField(blank=True, choices=[('needs_follow_up', '⚠️ 要フォロー'), ('urgent', '🔴 緊急対応必要'), ('parent_contacted', '📞 保護者連絡'), ('individual_talk', '🗣️ 個別面談'), ('shared_meeting', '👥 学年共有'), ('monitoring', '📝 継続観察')], help_text='先生のみが見る対応状況（生徒には非表示）', max_length=20, null=True, verbose_name='対応記録')),
                ('action_status', models.CharField(choices=[('pending', '未対応'), ('in_progress', '対応中'), ('completed', '対応済み'), ('not_required', '対応不要')], default='pending', help_text='internal_actionの対応状況を管理', max_length=20, verbose_name='対応状況')),
                ('action_completed_at', models.DateTimeField(blank=True, help_text='対応完了にした日時', null=True, verbose_name='対応完了日時')),
                ('action_note', models.CharField(blank=True, help_text='どのように対応したかを簡潔に記録（引継ぎ・保護者面談で活用）', max_length=200, null=True, verbose_name='対応内容メモ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('action_completed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='対応完了にした担任', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='対応者')),
                ('classroom', models.ForeignKey(blank=True, db_constraint=False, help_text='記載時の所属クラス（年度・学年・組）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diary.classroom', verbose_name='所属クラス')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='既読者(担任)')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
            ],
            options={
                'verbose_name': 'historical 連絡帳エントリー',
                'verbose_name_plural': 'historical 連絡帳エントリー',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '生徒'), ('teacher', '担任'), ('grade_leader', '学年主任'), ('school_leader', '教頭/校長')], default='student', help_text='ユーザーの役割（アクセス権限を自動的に設定）', max_length=20, verbose_name='役割')),
                ('managed_grade', models.IntegerField(blank=True, help_text='学年主任の場合、管理する学年（1, 2, 3）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='管理学年')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'historical ユーザープロフィール',
                'verbose_name_plural': 'historical ユーザープロフィール',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
