# Generated by Django 5.1.12 on 2025-10-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_historicaldiaryentry_historicaluserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDiaryEntry',
        ),
    ]
