# Generated by Django 5.1.12 on 2025-10-13 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_delete_historicaldiaryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('status', models.CharField(choices=[('present', '出席'), ('absent', '欠席'), ('late', '遅刻'), ('early_leave', '早退')], default='present', max_length=20, verbose_name='出席状況')),
                ('absence_reason', models.CharField(blank=True, choices=[('illness', '病気'), ('family', '家庭の都合'), ('other', 'その他')], help_text='欠席の場合のみ必須', max_length=20, null=True, verbose_name='欠席理由')),
                ('noted_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='diary.classroom', verbose_name='クラス')),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL, verbose_name='記録者（担任）')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
            ],
            options={
                'verbose_name': '出席記録',
                'verbose_name_plural': '出席記録',
                'ordering': ['-date', 'student__last_name', 'student__first_name'],
                'indexes': [models.Index(fields=['date'], name='diary_daily_date_9ace4e_idx'), models.Index(fields=['status'], name='diary_daily_status_70cfbf_idx'), models.Index(fields=['absence_reason'], name='diary_daily_absence_014d02_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
