# Generated by Django 5.1.12 on 2025-10-17 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_dailyattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNoteReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='既読日時')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='diary.teachernote', verbose_name='担任メモ')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_read_statuses', to=settings.AUTH_USER_MODEL, verbose_name='担任')),
            ],
            options={
                'verbose_name': '担任メモ既読状態',
                'verbose_name_plural': '担任メモ既読状態',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['teacher', 'note'], name='diary_teach_teacher_abeb82_idx')],
                'unique_together': {('teacher', 'note')},
            },
        ),
    ]
