# Generated by Django 5.1.12 on 2025-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_teachernotereadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'システム管理者'), ('student', '生徒'), ('teacher', '担任'), ('grade_leader', '学年主任'), ('school_leader', '教頭/校長')], default='student', help_text='ユーザーの役割（アクセス権限を自動的に設定）', max_length=20, verbose_name='役割'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'システム管理者'), ('student', '生徒'), ('teacher', '担任'), ('grade_leader', '学年主任'), ('school_leader', '教頭/校長')], default='student', help_text='ユーザーの役割（アクセス権限を自動的に設定）', max_length=20, verbose_name='役割'),
        ),
    ]
