# Generated by Django 5.1.12 on 2025-10-18 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_alter_historicaluserprofile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='assistant_teachers',
            field=models.ManyToManyField(blank=True, help_text='副担任や学年主任など、このクラスの連絡帳を閲覧できる先生を設定', related_name='assistant_classes', to=settings.AUTH_USER_MODEL, verbose_name='副担任'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL, verbose_name='主担任'),
        ),
    ]
