# Generated by Django 5.1.12 on 2025-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_classroom_assistant_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='requires_password_change',
            field=models.BooleanField(default=False, help_text='初回ログイン時にパスワード変更を強制します（管理者が仮パスワードで作成した場合）', verbose_name='パスワード変更が必要'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requires_password_change',
            field=models.BooleanField(default=False, help_text='初回ログイン時にパスワード変更を強制します（管理者が仮パスワードで作成した場合）', verbose_name='パスワード変更が必要'),
        ),
    ]
