# Generated by Django 5.1.12 on 2025-10-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalaction',
            options={'ordering': ['-created_at'], 'verbose_name': '承認操作', 'verbose_name_plural': '承認操作'},
        ),
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '承認申請', 'verbose_name_plural': '承認申請'},
        ),
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'ordering': ['workflow', 'order'], 'verbose_name': '承認ステップ', 'verbose_name_plural': '承認ステップ'},
        ),
        migrations.AlterModelOptions(
            name='approvalworkflow',
            options={'ordering': ['name'], 'verbose_name': '承認ワークフロー', 'verbose_name_plural': '承認ワークフロー'},
        ),
        migrations.AlterModelOptions(
            name='historicalapprovalrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 承認申請', 'verbose_name_plural': 'historical 承認申請'},
        ),
        migrations.AlterModelOptions(
            name='historicalapprovalworkflow',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 承認ワークフロー', 'verbose_name_plural': 'historical 承認ワークフロー'},
        ),
    ]
