# Generated by Django 5.1.12 on 2025-10-05 04:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='システム内で使用する一意の識別子（例: book_import_mapping）', max_length=100, unique=True, verbose_name='マッピングコード')),
                ('name', models.CharField(max_length=200, verbose_name='マッピング名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('model_name', models.CharField(help_text='例: library.Book', max_length=200, verbose_name='モデル名')),
                ('field_mapping', models.JSONField(default=dict, help_text="{'CSVカラム名': 'モデルフィールド名'}", verbose_name='フィールドマッピング')),
                ('validation_rules', models.JSONField(default=dict, help_text='フィールドごとのバリデーション設定', verbose_name='バリデーションルール')),
                ('unique_fields', models.JSONField(default=list, help_text='重複チェックに使用するフィールドのリスト', verbose_name='一意フィールド')),
                ('duplicate_strategy', models.CharField(choices=[('skip', 'スキップ'), ('update', '更新'), ('renumber', '新規採番'), ('error', 'エラー')], default='skip', max_length=20, verbose_name='重複時の処理')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_import_mappings', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'インポートマッピング',
                'verbose_name_plural': 'インポートマッピング',
                'db_table': 'kits_import_mappings',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='元ファイル名')),
                ('file', models.FileField(blank=True, upload_to='imports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv', 'txt', 'xlsx', 'xls'])], verbose_name='ファイル')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='ファイルサイズ（bytes）')),
                ('encoding', models.CharField(default='utf-8', max_length=50, verbose_name='文字コード')),
                ('model_name', models.CharField(max_length=200, verbose_name='モデル名')),
                ('parameters', models.JSONField(default=dict, help_text='インポート時の設定', verbose_name='パラメータ')),
                ('status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗'), ('partial', '一部成功')], default='pending', max_length=20, verbose_name='ステータス')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='総行数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功件数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失敗件数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='スキップ件数')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='更新件数')),
                ('renumbered_count', models.PositiveIntegerField(default=0, verbose_name='新規採番件数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('error_details', models.JSONField(default=list, help_text='各行のエラー情報', verbose_name='エラー詳細')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_histories', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_histories', to='io.importmapping', verbose_name='マッピング')),
            ],
            options={
                'verbose_name': 'インポート履歴',
                'verbose_name_plural': 'インポート履歴',
                'db_table': 'kits_import_histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['imported_by', 'status'], name='kits_import_importe_346c7e_idx'), models.Index(fields=['created_at'], name='kits_import_created_f9e1df_idx'), models.Index(fields=['status'], name='kits_import_status_e8131c_idx')],
            },
        ),
    ]
