# Generated by Django 5.1.12 on 2025-10-05 03:33

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='システム内で使用する一意の識別子(例: monthly_overtime_report)', max_length=100, unique=True, verbose_name='テンプレートコード')),
                ('name', models.CharField(max_length=200, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('model_name', models.CharField(blank=True, help_text='例: kits.demos.models.OvertimeRequest', max_length=200, verbose_name='モデル名')),
                ('query_template', models.TextField(blank=True, help_text='Django ORM形式のクエリ(Pythonコード)', verbose_name='クエリテンプレート')),
                ('chart_config', models.JSONField(default=dict, help_text='Chart.js設定(JSON形式)', verbose_name='グラフ設定')),
                ('supported_formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('html', 'HTML')], max_length=10), default=list, size=None, verbose_name='対応形式')),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='デフォルト形式')),
                ('html_template', models.CharField(blank=True, help_text='例: reports/monthly_overtime.html', max_length=255, verbose_name='HTMLテンプレートパス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_public', models.BooleanField(default=False, help_text='全ユーザーがアクセス可能か', verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'レポートテンプレート',
                'verbose_name_plural': 'レポートテンプレート',
                'db_table': 'kits_report_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='スケジュール名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('cron_expression', models.CharField(default='0 9 1 * *', help_text="例: '0 9 * * 1' = 毎週月曜日9:00AM", max_length=100, verbose_name='Cron式')),
                ('parameters', models.JSONField(default=dict, verbose_name='パラメータ')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='形式')),
                ('send_to_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='送信先メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最終実行日時')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='次回実行予定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_to_users', models.ManyToManyField(blank=True, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='送信先ユーザー')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'レポートスケジュール',
                'verbose_name_plural': 'レポートスケジュール',
                'db_table': 'kits_report_schedules',
                'ordering': ['next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='形式')),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'xlsx', 'html'])], verbose_name='ファイル')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='ファイルサイズ(bytes)')),
                ('parameters', models.JSONField(default=dict, help_text='レポート生成時のフィルタ条件など', verbose_name='パラメータ')),
                ('status', models.CharField(choices=[('pending', '生成待ち'), ('generating', '生成中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='ステータス')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成日時')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='有効期限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='データ行数')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='ダウンロード回数')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='生成者')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reporttemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'レポート',
                'verbose_name_plural': 'レポート',
                'db_table': 'kits_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['generated_by', 'status'], name='kits_report_generat_e79753_idx'), models.Index(fields=['created_at'], name='kits_report_created_732154_idx'), models.Index(fields=['expires_at'], name='kits_report_expires_1aa66b_idx')],
            },
        ),
    ]
