#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# collectstatic is now run during CI/CD build phase
# python /app/manage.py collectstatic --noinput

exec gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --workers 2
